# Generated by Django 4.1.1 on 2022-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_category_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(default='category/vid4.mp4', upload_to='category'),
        ),
    ]
