# Generated by Django 4.1.2 on 2022-10-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item',
            field=models.IntegerField(default=1),
        ),
    ]
