# Generated by Django 4.1.2 on 2022-10-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_orderitem_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
