# Generated by Django 4.1.2 on 2022-10-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_order_transaction_id_order_payment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
