# Generated by Django 4.1.2 on 2022-10-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
    ]
