# Generated by Django 4.1.2 on 2022-10-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_order_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(blank=True, default='a', max_length=36, null=True, unique=True),
        ),
    ]
