# Generated by Django 4.1.2 on 2022-10-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_order_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
