# Generated by Django 4.1.2 on 2022-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_order_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
