# Generated by Django 4.1.2 on 2022-10-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
    ]
