# Generated by Django 4.1.2 on 2022-10-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_remove_order_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('cart_code', models.CharField(max_length=255)),
                ('pay_code', models.CharField(max_length=36)),
                ('phone', models.CharField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.CharField(max_length=255)),
                ('admin_update', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
