# Generated by Django 4.1.2 on 2022-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_rename_date_added_shippingaddress_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cart_code',
            new_name='order_code',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order_code',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
