# Generated by Django 4.1.2 on 2022-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_rename_cart_code_payment_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order_code',
            field=models.CharField(max_length=255),
        ),
    ]
